from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(PointFileModel)
admin.site.register(LatLongModel)
admin.site.register(PostModel)
admin.site.register(SharePage)
admin.site.register(Post_urn)
admin.site.register(ImageModel)
admin.site.register(User)
admin.site.register(InviteEmploye)
admin.site.register(SocialStats)
admin.site.register(Company)
admin.site.register(CeleryTask)
admin.site.register(Wilayas)
admin.site.register(WilayasVehicle)
admin.site.register(WilayaScore)
admin.site.register(WilayaPopulation)
admin.site.register(WilayaBusiness)
admin.site.register(WilayaCompanies)
admin.site.register(WilayaMetrics)
admin.site.register(WilayaSchool)
admin.site.register(ScoreCoeff)
